[program:epatrol-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/epatrol/backend/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=epatrol
numprocs=3
redirect_stderr=true
stdout_logfile=/home/epatrol/backend/storage/logs/worker.log
stopwaitsecs=3600
